spring:
  application:
    name: emprendeStore
  datasource:
    # probar en local
    url: jdbc:mysql://localhost:3307/DB_ES
    username: root
    password: mysql
    #url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED
    #username: ridemofi
    #password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.resend.com      # Cambiado a Resend
    port: 587                  # Puerto estándar para TLS
    username: resend           # Siempre es "resend"
    password: ${RESEND_API_KEY} # Tu nueva API Key va aquí (en variable de entorno)
    from: onboarding@ridemofi.me # Correo de tu dominio verificado
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
